### ISSUE TITLE
GET Some ERROR when I run lenskit-hello

### ISSUE THREAD

**Issue by shayue111** [lenskit/lenskit-hello#8]
Dear Sir, I meet some Errors When I import the build.gradle in IDEA or just run it on shell. I google it and don't find relative ways to tackle it so I wish you can help me.

```bash
shayueMBP:lenskit-hello-master 2 shayue$ ./gradlew build
:compileJava

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compileClasspath'.
> Could not resolve org.lenskit:lenskit-all:3.0-M2.
  Required by:
      :lenskit-hello-master 2:unspecified
   > Could not resolve org.lenskit:lenskit-all:3.0-M2.
      > Could not get resource 'https://repo1.maven.org/maven2/org/lenskit/lenskit-all/3.0-M2/lenskit-all-3.0-M2.pom'.
         > Could not GET 'https://repo1.maven.org/maven2/org/lenskit/lenskit-all/3.0-M2/lenskit-all-3.0-M2.pom'.
            > repo1.maven.org:443 failed to respond
   > Could not resolve org.lenskit:lenskit-all:3.0-M2.
      > Could not get resource 'https://oss.sonatype.org/content/repositories/snapshots/org/lenskit/lenskit-all/3.0-M2/lenskit-all-3.0-M2.pom'.
         > Could not GET 'https://oss.sonatype.org/content/repositories/snapshots/org/lenskit/lenskit-all/3.0-M2/lenskit-all-3.0-M2.pom'.
            > oss.sonatype.org:443 failed to respond

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by mdekstrand** [comment]
It looks like Gradle is unable to communicate with the Maven server. This is likely an ephemeral problem; trying again may fix it.

If that does not fix it, then there is likely a problem with your network configuration.

**Comment by shayue111** [comment]
Maybe the Gradle version is too high? The version is Gradle 5.4.

**Comment by shayue111** [comment]
> It looks like Gradle is unable to communicate with the Maven server. This is likely an ephemeral problem; trying again may fix it.
> 
> If that does not fix it, then there is likely a problem with your network configuration.

Maybe the Gradle version is too high? The version is Gradle 5.4.

**Comment by mdekstrand** [comment]
When you use `./gradlew`, it downloads a local version of Gradle to build your program. I re-ran this on my Linux computer and it worked fine - it's possible that it's a problem with your local Java, but I really have no idea.
